version: "3.7"

services:
  dashboard:
    build:
      args:
        user: linkyi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: linkyi-dashboard
    container_name: linkyi-dashboard
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - "127.0.0.1:9001:9001"
    networks:
      - linkyi-bridge

  nginx:
    image: nginx:alpine
    container_name: linkyi-dashboard-nginx
    restart: unless-stopped
    ports:
      - 127.0.0.1:8022:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - linkyi-bridge

networks:
  linkyi-bridge:
    external: true
