version: "3.7"

services:
  app:
    build:
      args:
        user: linkyi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: linkyi-dashboard
    container_name: linkyi-dashboard
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - linkyi-bridge

  nginx:
    image: nginx:alpine
    container_name: linkyi-nginx
    restart: unless-stopped
    ports:
      - 8022:80
    volumes:
      - ./:/var/www
      - ~/data/nginx:/etc/nginx/conf.d/
    networks:
      - linkyi-bridge
